/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.core.foundation.tool.mcp;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.openjiuwen.core.common.exception.BaseError;
import com.openjiuwen.core.common.exception.StatusCode;
import com.openjiuwen.core.common.exception.ValidationError;
import com.openjiuwen.core.foundation.tool.schema.McpToolInfo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Tests for McpTool, McpToolCard, and McpServerConfig.
 * Ported from Python: tests/unit_tests/core/foundation/tool/test_streamable_http_client.py
 */
class McpToolTest {
    // ============================== McpServerConfig tests ==============================
    @Nested
    @DisplayName("McpServerConfig tests")
    class McpServerConfigTests {
        @Test
        @DisplayName("Default clientType is 'sse'")
        void testDefaultClientType() {
            McpServerConfig config =
                McpServerConfig.builder().serverName("test-server").serverPath("http://127.0.0.1:8930/mcp").build();
            assertEquals("sse", config.getClientType());
        }

        @Test
        @DisplayName("Defaults serverId to serverName when not provided")
        void testAutoGeneratedServerId() {
            McpServerConfig config =
                McpServerConfig.builder().serverName("test-server").serverPath("http://127.0.0.1:8930/mcp").build();
            assertEquals("test-server", config.getServerId());
        }

        @Test
        @DisplayName("Custom values are accepted")
        void testCustomValues() {
            McpServerConfig config =
                McpServerConfig.builder().serverName("my-server").serverPath("http://localhost:3000/mcp")
                        .clientType("streamable-http").authHeaders(Map.of("Authorization", "Bearer token"))
                        .authQueryParams(Map.of("ak", "demo-ak")).params(Map.of("key", "value")).build();

            assertEquals("my-server", config.getServerName());
            assertEquals("http://localhost:3000/mcp", config.getServerPath());
            assertEquals("streamable-http", config.getClientType());
            assertEquals("Bearer token", config.getAuthHeaders().get("Authorization"));
            assertEquals("demo-ak", config.getAuthQueryParams().get("ak"));
            assertEquals("value", config.getParams().get("key"));
        }

        @Test
        @DisplayName("NO_TIMEOUT constant is -1")
        void testNoTimeoutConstant() {
            assertEquals(-1, McpServerConfig.NO_TIMEOUT);
        }

        @Test
        @DisplayName("Default authHeaders and authQueryParams are empty maps")
        void testDefaultEmptyMaps() {
            McpServerConfig config =
                McpServerConfig.builder().serverName("test").serverPath("http://localhost").build();

            assertNotNull(config.getAuthHeaders());
            assertTrue(config.getAuthHeaders().isEmpty());
            assertNotNull(config.getAuthQueryParams());
            assertTrue(config.getAuthQueryParams().isEmpty());
            assertNotNull(config.getParams());
            assertTrue(config.getParams().isEmpty());
        }
    }

    // ============================== McpToolCard tests ==============================

    @Nested
    @DisplayName("McpToolCard tests")
    class McpToolCardTests {
        @Test
        @DisplayName("McpToolCard stores serverName")
        void testServerName() {
            McpToolCard card = McpToolCard.builder().name("browser_navigate").description("Navigate to URL")
                    .serverName("streamable-server").inputParams(Map.of("type", "object", "properties",
                            Map.of("url", Map.of("type", "string")), "required", new String[]{"url"}))
                    .build();

            assertEquals("browser_navigate", card.getName());
            assertEquals("Navigate to URL", card.getDescription());
            assertEquals("streamable-server", card.getServerName());
        }

        @Test
        @DisplayName("McpToolCard default serverId is empty string")
        void testDefaultServerId() {
            McpToolCard card = McpToolCard.builder().name("test").description("test").serverName("server").build();

            assertEquals("", card.getServerId());
        }

        @Test
        @DisplayName("toolInfo returns McpToolInfo with serverName")
        void testToolInfoReturnsMcpToolInfo() {
            McpToolCard card = McpToolCard.builder().name("browser_extract_text").description("Extract page text")
                    .serverName("mcp-server").inputParams(Map.of("type", "object")).build();

            McpToolInfo info = card.toolInfo();
            assertNotNull(info);
            assertEquals("browser_extract_text", info.getName());
            assertEquals("Extract page text", info.getDescription());
            assertEquals("mcp-server", info.getServerName());
            assertEquals(Map.of("type", "object"), info.getParameters());
        }

        @Test
        @DisplayName("Auto-generates id for McpToolCard")
        void testAutoGeneratedId() {
            McpToolCard card = McpToolCard.builder().name("test").description("test").serverName("server").build();
            assertNotNull(card.getId());
            assertFalse(card.getId().isEmpty());
        }
    }

    // ============================== McpTool tests ==============================

    @Nested
    @DisplayName("McpTool tests")
    class McpToolTests {
        /**
         * Simple mock MCP client for testing.
         */
        private static class MockMcpClient implements McpClient {
            private final Map<String, Object> callResults = new HashMap<>();
            private String lastCalledTool;
            private Map<String, Object> lastArguments;

            void setCallResult(String toolName, Object result) {
                callResults.put(toolName, result);
            }

            @Override
            public boolean connect(int retryTimes, float timeout) {
                return true;
            }

            @Override
            public boolean disconnect(float timeout) {
                return true;
            }

            @Override
            public List<Object> listTools(float timeout) {
                return List.of();
            }

            @Override
            public Object callTool(String toolName, Map<String, Object> arguments, float timeout) {
                lastCalledTool = toolName;
                lastArguments = arguments;
                return callResults.getOrDefault(toolName, "ok:" + toolName);
            }

            @Override
            public Optional<Object> getToolInfo(String toolName, float timeout) {
                return Optional.empty();
            }

            @Override
            public String getServerPath() {
                return "http://127.0.0.1:8930/mcp";
            }
        }

        @Test
        @DisplayName("McpTool invoke delegates to mcpClient.callTool")
        void testInvokeDelegatesToClient() throws Exception {
            MockMcpClient client = new MockMcpClient();
            client.setCallResult("browser_navigate", "navigation completed");

            McpToolCard card = McpToolCard.builder().name("browser_navigate").description("Navigate to URL")
                    .serverName("test-server").build();

            McpTool tool = new McpTool(client, card);
            Object result = tool.invoke(Map.of("url", "https://example.com"));

            assertNotNull(result);
            assertInstanceOf(Map.class, result);
            @SuppressWarnings("unchecked")
            Map<String, Object> resultMap = (Map<String, Object>) result;
            assertEquals("navigation completed", resultMap.get("result"));
            assertEquals("browser_navigate", client.lastCalledTool);
            assertEquals("https://example.com", client.lastArguments.get("url"));
        }

        @Test
        @DisplayName("McpTool invoke with null inputs uses empty map")
        void testInvokeNullInputs() throws Exception {
            MockMcpClient client = new MockMcpClient();
            client.setCallResult("test_tool", "ok");

            McpToolCard card = McpToolCard.builder().name("test_tool").description("test").serverName("server").build();

            McpTool tool = new McpTool(client, card);
            Object result = tool.invoke(null);

            assertNotNull(result);
            assertNotNull(client.lastArguments);
            assertTrue(client.lastArguments.isEmpty());
        }

        @Test
        @DisplayName("McpTool reports implicit extra fields as formatting errors")
        void testImplicitExtraFieldFailsDuringFormatting() {
            MockMcpClient client = new MockMcpClient();
            McpToolCard card = McpToolCard.builder()
                    .name("add_numbers")
                    .description("add numbers")
                    .serverName("server")
                    .inputParams(Map.of(
                            "properties", Map.of(
                                    "a", Map.of("type", "number"),
                                    "b", Map.of("type", "number")),
                            "required", List.of("a", "b"),
                            "type", "object"))
                    .build();
            McpTool tool = new McpTool(client, card);

            BaseError error = assertThrows(BaseError.class,
                    () -> tool.invoke(Map.of("a", 1, "b", 2, "c", 3)));

            assertEquals(StatusCode.TOOL_MCP_EXECUTION_ERROR.getCode(), error.getCode());
            assertTrue(error.getMessage().contains("format data with schema failed"));
            assertInstanceOf(ValidationError.class, error.getCause());
            assertNull(client.lastCalledTool);
        }

        @Test
        @DisplayName("McpTool stream throws not supported error")
        void testStreamThrowsNotSupported() {
            MockMcpClient client = new MockMcpClient();

            McpToolCard card = McpToolCard.builder().name("test_tool").description("test").serverName("server").build();

            McpTool tool = new McpTool(client, card);
            assertThrows(Throwable.class, () -> tool.stream(Map.of()));
        }

        @Test
        @DisplayName("McpTool constructor with null client throws exception")
        void testNullClientThrows() {
            McpToolCard card = McpToolCard.builder().name("test").description("test").serverName("server").build();

            assertThrows(Throwable.class, () -> new McpTool(null, card));
        }

        @Test
        @DisplayName("McpTool getCard returns the card")
        void testGetCard() {
            MockMcpClient client = new MockMcpClient();

            McpToolCard card = McpToolCard.builder().name("browser_navigate").description("Navigate page")
                    .serverName("streamable-server").build();

            McpTool tool = new McpTool(client, card);
            assertEquals("browser_navigate", tool.getCard().getName());
            assertEquals("Navigate page", tool.getCard().getDescription());
        }
    }
}
