/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.core.session;

import static org.junit.jupiter.api.Assertions.*;

import com.openjiuwen.core.session.internal.NodeSession;
import com.openjiuwen.core.session.internal.WorkflowSession;
import com.openjiuwen.core.session.state.InMemoryState;
import com.openjiuwen.core.session.state.WorkflowCommitState;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 * Tests for AgentSessionApi state operations.
 * <p>
 * Ported from Python's {@code test_session.py::TestSession::test_agent_session}.
 */
class AgentSessionApiTest {
    @Nested
    @DisplayName("AgentSessionApi state operations")
    class StateOps {
        @Test
        @DisplayName("update and get state")
        void testUpdateAndGet() {
            AgentSessionApi session = new AgentSessionApi("abc");
            Map<String, Object> data = Map.of("data", Map.of("a", 1));
            session.updateState(Map.of("result", data));
            assertEquals(Map.of("data", Map.of("a", 1)), session.getState("result"));
        }

        @Test
        @DisplayName("merge update preserves existing nested values")
        void testMergeUpdate() {
            AgentSessionApi session = new AgentSessionApi("abc");
            session.updateState(Map.of("result", Map.of("data", Map.of("a", 1))));
            assertEquals(Map.of("data", Map.of("a", 1)), session.getState("result"));

            session.updateState(Map.of("result", Map.of("data", Map.of("b", 1))));
            assertEquals(Map.of("data", Map.of("a", 1, "b", 1)), session.getState("result"));
        }

        @Test
        @DisplayName("null update removes key")
        void testNullUpdate() {
            AgentSessionApi session = new AgentSessionApi("abc");
            Map<String, Object> data2 = Map.of("data", Map.of("b", 1));
            session.updateState(Map.of("result", data2));
            assertEquals(Map.of("data", Map.of("b", 1)), session.getState("result"));

            Map<String, Object> nullUpdate = new HashMap<>();
            nullUpdate.put("result", null);
            session.updateState(nullUpdate);
            assertNull(session.getState("result"));
        }

        @Test
        @DisplayName("re-set after null update")
        void testResetAfterNull() {
            AgentSessionApi session = new AgentSessionApi("abc");
            Map<String, Object> data2 = Map.of("data", Map.of("b", 1));
            session.updateState(Map.of("result", data2));

            Map<String, Object> nullUpdate = new HashMap<>();
            nullUpdate.put("result", null);
            session.updateState(nullUpdate);
            assertNull(session.getState("result"));

            session.updateState(Map.of("result", Map.of("data", Map.of("b", 1))));
            assertEquals(Map.of("data", Map.of("b", 1)), session.getState("result"));
        }

        @Test
        @DisplayName("dump state returns correct structure")
        void testDumpState() {
            AgentSessionApi session = new AgentSessionApi("abc");
            session.updateState(Map.of("result", Map.of("data", Map.of("b", 1))));

            Map<String, Object> dump = session.dumpState();
            assertNotNull(dump);
            assertTrue(dump.containsKey("global_state"));
            assertTrue(dump.containsKey("agent_state"));
            assertTrue(dump.containsKey("trace_state"));

            @SuppressWarnings("unchecked")
            Map<String, Object> globalState = (Map<String, Object>) dump.get("global_state");
            assertNotNull(globalState);
            assertEquals(Map.of("data", Map.of("b", 1)), globalState.get("result"));
        }

        @Test
        @DisplayName("session ID is preserved")
        void testSessionId() {
            AgentSessionApi session = new AgentSessionApi("test-id-123");
            assertEquals("test-id-123", session.getSessionId());
        }

        @Test
        @DisplayName("auto-generated session ID when null")
        void testAutoGeneratedSessionId() {
            AgentSessionApi session = new AgentSessionApi();
            assertNotNull(session.getSessionId());
            assertFalse(session.getSessionId().isEmpty());
        }

        @Test
        @DisplayName("environment variables via constructor")
        void testEnvVars() {
            AgentSessionApi session = new AgentSessionApi("test", Map.of("env_key", "env_val"));
            assertEquals("env_val", session.getEnv("env_key"));
            assertNull(session.getEnv("non_existent"));
        }

        @Test
        @DisplayName("getEnv with default value")
        void testGetEnvDefault() {
            AgentSessionApi session = new AgentSessionApi("test");
            assertEquals("default_val", session.getEnv("missing", "default_val"));
        }

        @Test
        @DisplayName("streamIterator yields output chunks")
        void testStreamIterator() {
            AgentSessionApi session = new AgentSessionApi("stream-test");
            session.preRun(Map.of());
            session.writeCustomStream(Map.of("key", "value1"));
            session.writeCustomStream(Map.of("key", "value2"));
            session.postRun();

            Iterator<Object> iterator = session.streamIterator();
            assertTrue(iterator.hasNext());
            assertNotNull(iterator.next());
            assertTrue(iterator.hasNext());
            assertNotNull(iterator.next());
            assertFalse(iterator.hasNext());
        }
    }

    @Nested
    @DisplayName("NodeSessionApi state operations")
    class NodeSessionApiOps {
        @Test
        @DisplayName("node session update and commit cycle")
        void testUpdateAndCommit() {
            WorkflowCommitState state = InMemoryState.create();
            WorkflowSession wf = new WorkflowSession("wf1", null, null, state, null);
            NodeSession nodeSession = new NodeSession(wf, "node1");
            NodeSessionApi session = new NodeSessionApi(nodeSession);

            // Update component state (not committed yet)
            session.updateState(Map.of("key1", "value1"));
            session.updateState(Map.of("key2", Map.of("nested_key", "nested_value")));

            // Update global state
            session.updateGlobalState(Map.of("global_key1", "global_value1"));
            session.updateGlobalState(Map.of("global_key2", Map.of("nested_global_key", "nested_global_value")));

            // Before commit, state is not visible
            assertNull(session.getState("key1"));
            assertNull(session.getState("key2"));
            assertNull(session.getGlobalState("global_key1"));
            assertNull(session.getGlobalState("global_key2"));
        }

        @Test
        @DisplayName("dump state before commit shows updates")
        void testDumpStateBeforeCommit() {
            WorkflowCommitState state = InMemoryState.create();
            WorkflowSession wf = new WorkflowSession("wf1", null, null, state, null);
            NodeSession nodeSession = new NodeSession(wf, "node1");
            NodeSessionApi session = new NodeSessionApi(nodeSession);

            session.updateState(Map.of("key1", "value1"));
            session.updateGlobalState(Map.of("global_key1", "global_value1"));

            Map<String, Object> dump = session.dumpState();
            assertNotNull(dump);
            assertTrue(dump.containsKey("io_state"));
            assertTrue(dump.containsKey("global_state"));
            assertTrue(dump.containsKey("comp_state"));
            assertTrue(dump.containsKey("global_state_updates"));
            assertTrue(dump.containsKey("comp_state_updates"));
            assertTrue(dump.containsKey("trace_state"));

            // global_state should be empty before commit
            @SuppressWarnings("unchecked")
            Map<String, Object> globalState = (Map<String, Object>) dump.get("global_state");
            assertTrue(globalState.isEmpty());

            // global_state_updates should have pending data
            @SuppressWarnings("unchecked")
            Map<String, Object> globalUpdates = (Map<String, Object>) dump.get("global_state_updates");
            assertFalse(globalUpdates.isEmpty());
        }

        @Test
        @DisplayName("state visible after commit")
        void testStateVisibleAfterCommit() {
            WorkflowCommitState state = InMemoryState.create();
            WorkflowSession wf = new WorkflowSession("wf1", null, null, state, null);
            NodeSession nodeSession = new NodeSession(wf, "node1");
            NodeSessionApi session = new NodeSessionApi(nodeSession);

            session.updateState(Map.of("key1", "value1"));
            session.updateState(Map.of("key2", Map.of("nested_key", "nested_value")));
            session.updateGlobalState(Map.of("global_key1", "global_value1"));
            session.updateGlobalState(Map.of("global_key2", Map.of("nested_global_key", "nested_global_value")));

            // Commit all state
            state.commit();

            assertEquals("value1", session.getState("key1"));
            assertEquals(Map.of("nested_key", "nested_value"), session.getState("key2"));
            assertEquals("global_value1", session.getGlobalState("global_key1"));
            assertEquals(Map.of("nested_global_key", "nested_global_value"), session.getGlobalState("global_key2"));
        }

        @Test
        @DisplayName("dump state after commit shows committed state")
        void testDumpStateAfterCommit() {
            WorkflowCommitState state = InMemoryState.create();
            WorkflowSession wf = new WorkflowSession("wf1", null, null, state, null);
            NodeSession nodeSession = new NodeSession(wf, "node1");
            NodeSessionApi session = new NodeSessionApi(nodeSession);

            session.updateState(Map.of("key1", "value1"));
            session.updateState(Map.of("key2", Map.of("nested_key", "nested_value")));
            session.updateGlobalState(Map.of("global_key1", "global_value1"));

            state.commit();

            Map<String, Object> dump = session.dumpState();
            @SuppressWarnings("unchecked")
            Map<String, Object> globalState = (Map<String, Object>) dump.get("global_state");
            assertEquals("global_value1", globalState.get("global_key1"));

            // After commit, updates should be empty
            @SuppressWarnings("unchecked")
            Map<String, Object> globalUpdates = (Map<String, Object>) dump.get("global_state_updates");
            assertTrue(globalUpdates.isEmpty());
        }

        @Test
        @DisplayName("node session executable ID and workflow ID")
        void testNodeSessionIds() {
            WorkflowCommitState state = InMemoryState.create();
            WorkflowSession wf = new WorkflowSession("wf1", null, null, state, null);
            NodeSession nodeSession = new NodeSession(wf, "node1");
            NodeSessionApi session = new NodeSessionApi(nodeSession);

            assertEquals("wf1", session.getWorkflowId());
            assertEquals("node1", session.getComponentId());
            assertEquals("node1", session.getExecutableId());
        }
    }
}
