/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.agentteams.interaction;

/**
 * Event forwarded to a human-agent's SDK inbound callback.
 *
 * <p>Mirrors Python {@code interaction/payload.py:HumanAgentInboundEvent}. The
 * leader observes every MESSAGE / BROADCAST event on the team topic; for
 * messages addressed to a human agent (or broadcasts), the leader fires the
 * recipient's registered callback with this payload so the SDK can surface the
 * inbound to the controlling human.
 *
 * @param memberName recipient member name (the human agent)
 * @param sender sender member name
 * @param body message content
 * @param isBroadcast whether this was a broadcast (vs direct)
 * @param messageId team message id
 * @param timestamp millisecond UTC epoch, or {@code 0} when unknown
 * @since 2026/7/9
 */
public record HumanAgentInboundEvent(
        String memberName,
        String sender,
        String body,
        boolean isBroadcast,
        String messageId,
        long timestamp
) {
    // empty: event payload tuple; accessors generated by compiler
}
