/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.agentteams.interaction;

/**
 * MentionRoute.
 * 
 * @since 0.1.7
 */
public record MentionRoute(String target, String body) {
    // empty: route pair; accessors generated by compiler
}
