/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.agentteams.agent.coordination;

import com.openjiuwen.agentteams.messager.Messager;
import com.openjiuwen.agentteams.tools.TeamBackend;
import com.openjiuwen.agentteams.tools.TeamMessageManager;
import com.openjiuwen.agentteams.tools.TeamTaskManager;

/**
 * Per-process container of team infrastructure services.
 *
 * <p>Mirrors Python {@code agent/infra.py:TeamInfra}. Holds the cross-cutting
 * managers a coordination handler needs: messager for transport publish,
 * team_backend for member / completion queries, task_manager for board scans,
 * message_manager for mailbox drains. Constructed once per
 * {@code CoordinationKernel.setup()} from the owning {@code TeamAgent}'s
 * fields and passed by reference into every handler.
 *
 * @since 2026/7/9
 */
public record TeamInfra(
        Messager messager,
        TeamBackend teamBackend,
        TeamTaskManager taskManager,
        TeamMessageManager messageManager
) {
    // empty: infra bundle; accessors generated by compiler
}
